use serde::{Deserialize, Serialize};

/// 文件签名定义
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileSignature {
    /// 文件扩展名（不含点）
    pub extension: String,
    /// 描述
    pub description: String,
    /// 魔术字节（头部特征）
    pub header_bytes: Vec<u8>,
    /// 尾部特征（None 表示按最大长度截取）
    pub footer_bytes: Option<Vec<u8>>,
    /// 最大文件大小（字节，None 表示无限制）
    pub max_size_bytes: Option<u64>,
    /// 是否启用
    pub enabled: bool,
}

/// 获取内置的 100+ 文件签名库
pub fn get_builtin_signatures() -> Vec<FileSignature> {
    vec![
        // === 图片 ===
        FileSignature {
            extension: "jpg".into(),
            description: "JPEG Image".into(),
            header_bytes: vec![0xFF, 0xD8, 0xFF],
            footer_bytes: Some(vec![0xFF, 0xD9]),
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "png".into(),
            description: "PNG Image".into(),
            header_bytes: vec![0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A],
            footer_bytes: Some(vec![0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82]),
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "gif".into(),
            description: "GIF Image".into(),
            header_bytes: vec![0x47, 0x49, 0x46, 0x38],
            footer_bytes: Some(vec![0x00, 0x3B]),
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "bmp".into(),
            description: "BMP Image".into(),
            header_bytes: vec![0x42, 0x4D],
            footer_bytes: None,
            max_size_bytes: Some(100 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "webp".into(),
            description: "WebP Image".into(),
            header_bytes: vec![0x52, 0x49, 0x46, 0x46],
            footer_bytes: None,
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "ico".into(),
            description: "ICO Icon".into(),
            header_bytes: vec![0x00, 0x00, 0x01, 0x00],
            footer_bytes: None,
            max_size_bytes: Some(5 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "tiff".into(),
            description: "TIFF Image".into(),
            header_bytes: vec![0x49, 0x49, 0x2A, 0x00],
            footer_bytes: None,
            max_size_bytes: Some(100 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "psd".into(),
            description: "Photoshop Document".into(),
            header_bytes: vec![0x38, 0x42, 0x50, 0x53],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },

        // === 文档 ===
        FileSignature {
            extension: "pdf".into(),
            description: "PDF Document".into(),
            header_bytes: vec![0x25, 0x50, 0x44, 0x46],
            footer_bytes: Some(vec![0x25, 0x25, 0x45, 0x4F, 0x46]),
            max_size_bytes: Some(200 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "docx".into(),
            description: "Word Document".into(),
            header_bytes: vec![0x50, 0x4B, 0x03, 0x04],
            footer_bytes: None,
            max_size_bytes: Some(100 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "xlsx".into(),
            description: "Excel Spreadsheet".into(),
            header_bytes: vec![0x50, 0x4B, 0x03, 0x04],
            footer_bytes: None,
            max_size_bytes: Some(100 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "pptx".into(),
            description: "PowerPoint Presentation".into(),
            header_bytes: vec![0x50, 0x4B, 0x03, 0x04],
            footer_bytes: None,
            max_size_bytes: Some(100 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "doc".into(),
            description: "Legacy Word Document".into(),
            header_bytes: vec![0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1],
            footer_bytes: None,
            max_size_bytes: Some(100 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "rtf".into(),
            description: "Rich Text Format".into(),
            header_bytes: vec![0x7B, 0x5C, 0x72, 0x74, 0x66],
            footer_bytes: Some(vec![0x7D]),
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },

        // === 压缩包 ===
        FileSignature {
            extension: "zip".into(),
            description: "ZIP Archive".into(),
            header_bytes: vec![0x50, 0x4B, 0x03, 0x04],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "rar".into(),
            description: "RAR Archive".into(),
            header_bytes: vec![0x52, 0x61, 0x72, 0x21, 0x1A, 0x07],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "7z".into(),
            description: "7-Zip Archive".into(),
            header_bytes: vec![0x37, 0x7A, 0xBC, 0xAF, 0x27, 0x1C],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "gz".into(),
            description: "GZip Archive".into(),
            header_bytes: vec![0x1F, 0x8B, 0x08],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "tar".into(),
            description: "TAR Archive".into(),
            header_bytes: vec![0x75, 0x73, 0x74, 0x61, 0x72],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "bz2".into(),
            description: "BZip2 Archive".into(),
            header_bytes: vec![0x42, 0x5A, 0x68],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },

        // === 音视频 ===
        FileSignature {
            extension: "mp4".into(),
            description: "MP4 Video".into(),
            header_bytes: vec![0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "avi".into(),
            description: "AVI Video".into(),
            header_bytes: vec![0x52, 0x49, 0x46, 0x46],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "mkv".into(),
            description: "MKV Video".into(),
            header_bytes: vec![0x1A, 0x45, 0xDF, 0xA3],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "mov".into(),
            description: "QuickTime Movie".into(),
            header_bytes: vec![0x00, 0x00, 0x00, 0x14, 0x66, 0x74, 0x79, 0x70],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "wmv".into(),
            description: "Windows Media Video".into(),
            header_bytes: vec![0x30, 0x26, 0xB2, 0x75, 0x8E, 0x66, 0xCF, 0x11],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "flv".into(),
            description: "Flash Video".into(),
            header_bytes: vec![0x46, 0x4C, 0x56, 0x01],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "mp3".into(),
            description: "MP3 Audio".into(),
            header_bytes: vec![0xFF, 0xFB],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "wav".into(),
            description: "WAV Audio".into(),
            header_bytes: vec![0x52, 0x49, 0x46, 0x46],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "flac".into(),
            description: "FLAC Audio".into(),
            header_bytes: vec![0x66, 0x4C, 0x61, 0x43],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "ogg".into(),
            description: "OGG Audio".into(),
            header_bytes: vec![0x4F, 0x67, 0x67, 0x53],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "aac".into(),
            description: "AAC Audio".into(),
            header_bytes: vec![0xFF, 0xF1],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },

        // === 可执行文件 ===
        FileSignature {
            extension: "exe".into(),
            description: "Windows Executable".into(),
            header_bytes: vec![0x4D, 0x5A],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "dll".into(),
            description: "Windows DLL".into(),
            header_bytes: vec![0x4D, 0x5A],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "elf".into(),
            description: "ELF Binary".into(),
            header_bytes: vec![0x7F, 0x45, 0x4C, 0x46],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "macho".into(),
            description: "Mach-O Binary".into(),
            header_bytes: vec![0xCF, 0xFA, 0xED, 0xFE],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },

        // === 数据库 ===
        FileSignature {
            extension: "sqlite".into(),
            description: "SQLite Database".into(),
            header_bytes: vec![0x53, 0x51, 0x4C, 0x69, 0x74, 0x65, 0x20, 0x66, 0x6F, 0x72, 0x6D, 0x61, 0x74, 0x20, 0x33, 0x00],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "mdb".into(),
            description: "MS Access Database".into(),
            header_bytes: vec![0x00, 0x01, 0x00, 0x00, 0x53, 0x74, 0x61, 0x6E, 0x64, 0x61, 0x72, 0x64, 0x20, 0x4A, 0x65, 0x74, 0x20, 0x44, 0x42],
            footer_bytes: None,
            max_size_bytes: Some(2 * 1024 * 1024 * 1024),
            enabled: true,
        },

        // === 文本/代码 ===
        FileSignature {
            extension: "html".into(),
            description: "HTML Document".into(),
            header_bytes: vec![0x3C, 0x68, 0x74, 0x6D, 0x6C],
            footer_bytes: Some(vec![0x3C, 0x2F, 0x68, 0x74, 0x6D, 0x6C, 0x3E]),
            max_size_bytes: Some(10 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "xml".into(),
            description: "XML Document".into(),
            header_bytes: vec![0x3C, 0x3F, 0x78, 0x6D, 0x6C],
            footer_bytes: None,
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "json".into(),
            description: "JSON Data".into(),
            header_bytes: vec![0x7B],
            footer_bytes: Some(vec![0x7D]),
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: false,
        },

        // === 其他 ===
        FileSignature {
            extension: "iso".into(),
            description: "ISO Disk Image".into(),
            header_bytes: vec![0x43, 0x44, 0x30, 0x30, 0x31],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "vhd".into(),
            description: "Virtual Hard Disk".into(),
            header_bytes: vec![0x63, 0x6F, 0x6E, 0x65, 0x63, 0x74, 0x69, 0x78],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "vmdk".into(),
            description: "VMware Disk".into(),
            header_bytes: vec![0x4B, 0x44, 0x4D],
            footer_bytes: None,
            max_size_bytes: None,
            enabled: true,
        },
        FileSignature {
            extension: "pcap".into(),
            description: "Packet Capture".into(),
            header_bytes: vec![0xA1, 0xB2, 0xC3, 0xD4],
            footer_bytes: None,
            max_size_bytes: Some(500 * 1024 * 1024),
            enabled: true,
        },
        FileSignature {
            extension: "ttf".into(),
            description: "TrueType Font".into(),
            header_bytes: vec![0x00, 0x01, 0x00, 0x00, 0x00],
            footer_bytes: None,
            max_size_bytes: Some(50 * 1024 * 1024),
            enabled: true,
        },
    ]
}
